
@startuml Схема взаимодействия участников исследуемого объекта
    left to right direction

    actor "Покупатель" as Customer
    actor "Менеджер магазина" as Manager

    rectangle "Витрина/Склад" as Store
    rectangle "Телефон/Email" as Comm
        rectangle "Сайт-витрина\n(только информация)" as Landing

    Customer --> Store : Просмотр товаров
        Customer --> Landing : Просмотр информации\nКонтакты магазина
    Customer --> Manager : Звонок/Email для заказа
    Manager --> Store : Проверка наличия товара
    Manager --> Customer : Подтверждение заказа\nСогласование оплаты/доставки
    Manager --> Comm : Отправка реквизитов/информации
    Customer --> Manager : Оплата (наличные/перевод)
    Manager --> Customer : Передача товара/отправка

@enduml